### ISSUE TITLE
podman-compose compatible?

### ISSUE THREAD

**Issue by Akruidenberg** [RynoM/self-hosted-deployment#1]
I´ve migrated my containers to podman-compose. Is it possible to modify this git repo to make it compatible with podman-compose?

**Comment by RynoM** [comment]
I've never used podman, from a quick glance looking at it; You'd have to add podman-compose and whatever other package dependencies that or podman needs to the `Dockerfile` and change a couple lines in the gitea workflows. The only thing I'm not sure about is how you'd be able to use podman commands from within the container to execute things on the host. Right now this is done with docker by mounting the docker.sock, but I'm not sure how this would work with podman. Hope this gives you some idea at least.

**Comment by Akruidenberg** [comment]
Yes. Thats also the problem i have with podman-compose. Will try this out with podman+ docker-compose
